version: '3'
services:
    app:
        build: .
        depends_on:
            - mysql
        restart: "on-failure"
        volumes:
            - "appdata:/apps/subredditfetcher"
    mysql:
        image: mysql
        volumes:
            - "dbdata:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=dontusethisinprod
    adminer:
        image: adminer
        ports:
            - "8080:8080"

volumes:
    dbdata:
    appdata:
